name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: shephajona/tawacollegealumni.github.io@master
      env:
        HUGO_VERSION: 0.68.3
        TARGET_REPO: shephajona/shephajona.github.io
        TOKEN: ${{ secrets.TC_TOKEN }}
        CNAME: tawacollegealumni.co.nz
